version: "3.3"
services:
    ms_active:
        restart: unless-stopped
        build:
            context: /.
            dockerfile: Dockerfile
        volumes:
            - ./:/app
        ports:
            - 3333:80
      